### ISSUE TITLE
[QUESTION] Error when import Updater from telegram.ext in v13

### ISSUE THREAD

**Issue by Konano** [python-telegram-bot/python-telegram-bot#2120]
### Issue I am facing
I switched to V13, but it didn't seem to work.

### Traceback to the issue
```
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from telegram.ext import Updater
  File "/usr/local/lib/python3.7/dist-packages/telegram/__init__.py", line 23, in <module>
    from .user import User
  File "/usr/local/lib/python3.7/dist-packages/telegram/user.py", line 23, in <module>
    from telegram.utils.helpers import mention_html as util_mention_html
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/helpers.py", line 93, in <module>
    reference_timestamp: float = None, tzinfo: pytz.BaseTzInfo = None) -> float:
AttributeError: module 'pytz' has no attribute 'BaseTzInfo'
```

### Related part of your code
```python
from telegram.ext import Updater
```

**Comment by Poolitzer** [comment]
You might have a really old version of pytz for some reason. Can you check that?

```
pip show pytz
```

**Comment by Konano** [comment]
> You might have a really old version of pytz for some reason. Can you check that?
> 
> ```
> pip show pytz
> ```

Name: pytz
Version: 2014.10
Summary: World timezone definitions, modern and historical
Home-page: http://pythonhosted.org/pytz
Author: Stuart Bishop
Author-email: stuart@stuartbishop.net
License: MIT
Location: /usr/lib/python3/dist-packages
Requires:
Required-by: tzlocal, Mastodon.py, APScheduler

**Comment by Konano** [comment]
When I upgraded pytz to 2020.1, everything is OK.

**Comment by Poolitzer** [comment]
Alright, that is too old, we need at least 2018.6. I am really surprised you ended up with that old version, python should ship with it being newer.

Anyway, just do `pip install -U pytz` and try again, it should work.

**Comment by Konano** [comment]
> Alright, that is too old, we need at least 2018.6. I am really surprised you ended up with that old version, python should ship with it being newer.
> 
> Anyway, just do `pip install -U pytz` and try again, it should work.

Thanks! Can we check pytz version when upgrade to v13?

**Comment by Poolitzer** [comment]
Yeah I will add it to the requirements of our library

**Comment by Konano** [comment]
Can I try to make with a PR? Maybe i know how to add it.
