### ISSUE TITLE
Repeating job AttributeError

### ISSUE THREAD

**Issue by alexbagirov** [python-telegram-bot/python-telegram-bot#1031]
Hi!

I'm having a small def which is a repeating job, the code actually looks like this:
```
dp = updater.dispatcher
j = updater.job_queue
j.run_repeating(rss, 300)
```

After upgrading to 10.0.0 I get an exception in logs.

### Configuration
**Operating System:** Ubuntu

**Version of Python, python-telegram-bot & dependencies:**

python-telegram-bot 10.0.0
certifi 2018.01.18
future 0.16.0
Python 3.6.3 (default, Oct  6 2017, 08:44:35)

### Logs
```
AttributeError: 'NoneType' object has no attribute 'schedule_removal'
[03-03 23:51:50] [ERROR] [bot]
An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/conversationhandler.py", line 309, in handle_update
    timeout_job.schedule_removal()
AttributeError: 'NoneType' object has no attribute 'schedule_removal'
```

**Comment by Eldinnie** [comment]
@alexbagirov HI,

I would like to investigate what seems to be the problem. Can you please show the code for the Job in question aswell?

**Comment by alexbagirov** [comment]
@Eldinnie Hi, sure, you can find it [here](https://github.com/MoarCatz/nmaps-telegram/blob/ptb10/rss.py). Also my latest suggestion is that this exception is not connected with repeating job but something else. But I'm not sure :smiley:

**Comment by nmlorg** [comment]
It looks like [conversationhandler.py:308](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/ext/conversationhandler.py#L308) was [changed](https://github.com/python-telegram-bot/python-telegram-bot/pull/895/commits/f68fb0387230a9e29fe9d636d263ddecf2a7ce03) to no longer protect 309-310 properly. It should definitely be `timeout_job is not None and` any other conditions, not `or`; I guess it depends on if the intent was to timeout from the beginning of the conversation (which would require a couple other changes) or timeout from last interaction, and the doc strings suggest to me the latter, so I think it should just be reverted to `if timeout_job is not None:` or maybe simplified a little to:
```python
        new_state = self.current_handler.handle_update(update, dispatcher)
!       timeout_job = self.timeout_jobs.pop(self.current_conversation, None)

!       if timeout_job is not None:
            timeout_job.schedule_removal()
-           del self.timeout_jobs[self.current_conversation]
        if self.conversation_timeout and new_state != self.END:
```

**Comment by Eldinnie** [comment]
I think you;re absolutely right. We can take your snippet indeed.
Are you in the possibility to make a PR? And @tsnoam we should push a patch (10.1) for this. It makes every conversationhandler crash if timeout is not set en `ConversationHandler.END` is returned from a callback

**Comment by Eldinnie** [comment]
Seeing this has some priority IMO I';m picking this up.

**Comment by phDooY** [comment]
Not sure where to ask this, but why can not I open a new issue?
